import {
  Utensils,
  Car,
  Home,
  Shirt,
  Heart,
  Gamepad2,
  GraduationCap,
  Gift,
  Plane,
  ShoppingBag,
  Smartphone,
  Wifi,
  Zap,
  Droplets,
  CreditCard,
  PiggyBank,
  TrendingUp,
  Briefcase,
  Baby,
  Dog,
  Dumbbell,
  Pill,
  Scissors,
  Coffee,
  Beer,
  Music,
  Film,
  Book,
  Palette,
  Wrench,
  ShieldCheck,
  Banknote,
  Receipt,
  CircleDollarSign,
  HelpCircle,
  Wallet,
  ShoppingCart,
  DollarSign,
  Bus,
  // Новые иконки
  Footprints,
  Bike,
  Train,
  Fuel,
  ParkingCircle,
  Apple,
  Pizza,
  Soup,
  IceCream,
  Cookie,
  Wine,
  Martini,
  Cake,
  Candy,
  Beef,
  Fish,
  Milk,
  Salad,
  Sprout,
  PersonStanding,
  Users,
  School,
  Backpack,
  BookOpen,
  Pencil,
  Calculator,
  Stethoscope,
  Syringe,
  HeartPulse,
  Hospital,
  Tablets,
  Glasses,
  Watch,
  Gem,
  Sparkles,
  Crown,
  PartyPopper,
  Disc,
  Headphones,
  Camera,
  Video,
  Radio,
  Tv,
  Monitor,
  Laptop,
  Printer,
  Mouse,
  Keyboard,
  HardDrive,
  TreePine,
  Flower2,
  Leaf,
  Cat,
  Bird,
  Rabbit,
  Turtle,
  PawPrint,
  Bone,
  Bed,
  Sofa,
  Lamp,
  Bath,
  WashingMachine,
  Refrigerator,
  Microwave,
  UtensilsCrossed,
  Cigarette,
  Flame,
  Snowflake,
  Sun,
  Cloud,
  Umbrella,
  type LucideIcon,
} from 'lucide-react'

/**
 * Реестр всех доступных иконок
 * Ключ - это название иконки (например, 'shopping-cart', 'utensils')
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // Основные расходы
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  groceries: ShoppingBag,
  'shopping-bag': ShoppingBag,
  restaurants: Coffee,
  coffee: Coffee,
  car: Car,
  home: Home,
  zap: Zap,
  utilities: Zap,
  droplets: Droplets,
  water: Droplets,
  wifi: Wifi,
  internet: Wifi,
  smartphone: Smartphone,
  phone: Smartphone,

  // Транспорт
  bus: Bus,
  transport: Car,
  bike: Bike,
  bicycle: Bike,
  train: Train,
  fuel: Fuel,
  gas: Fuel,
  parking: ParkingCircle,
  'parking-circle': ParkingCircle,
  footprints: Footprints,
  walking: Footprints,

  // Еда и напитки
  apple: Apple,
  fruit: Apple,
  pizza: Pizza,
  soup: Soup,
  'ice-cream': IceCream,
  cookie: Cookie,
  cookies: Cookie,
  wine: Wine,
  martini: Martini,
  cocktail: Martini,
  cake: Cake,
  candy: Candy,
  sweets: Candy,
  beef: Beef,
  meat: Beef,
  fish: Fish,
  seafood: Fish,
  milk: Milk,
  dairy: Milk,
  salad: Salad,
  vegetables: Salad,
  sprout: Sprout,

  // Личные расходы
  shirt: Shirt,
  clothing: Shirt,
  heart: Heart,
  health: Heart,
  pill: Pill,
  medicine: Pill,
  dumbbell: Dumbbell,
  fitness: Dumbbell,
  gym: Dumbbell,
  sport: Dumbbell,
  scissors: Scissors,
  beauty: Scissors,
  haircut: Scissors,
  glasses: Glasses,
  watch: Watch,
  jewelry: Gem,
  gem: Gem,
  sparkles: Sparkles,
  crown: Crown,
  luxury: Crown,

  // Здоровье
  stethoscope: Stethoscope,
  doctor: Stethoscope,
  syringe: Syringe,
  vaccination: Syringe,
  'heart-pulse': HeartPulse,
  cardiology: HeartPulse,
  hospital: Hospital,
  clinic: Hospital,
  tablets: Tablets,
  medication: Tablets,

  // Развлечения
  gamepad2: Gamepad2,
  'gamepad-2': Gamepad2,
  entertainment: Gamepad2,
  games: Gamepad2,
  music: Music,
  film: Film,
  movies: Film,
  streaming: Film,
  book: Book,
  books: Book,
  'book-open': BookOpen,
  reading: BookOpen,
  palette: Palette,
  hobbies: Palette,
  art: Palette,
  'party-popper': PartyPopper,
  party: PartyPopper,
  celebration: PartyPopper,
  disc: Disc,
  cd: Disc,
  headphones: Headphones,
  audio: Headphones,
  camera: Camera,
  photo: Camera,
  photography: Camera,
  video: Video,
  recording: Video,
  radio: Radio,
  tv: Tv,
  television: Tv,

  // Образование и работа
  'graduation-cap': GraduationCap,
  education: GraduationCap,
  briefcase: Briefcase,
  work: Briefcase,
  business: Briefcase,
  school: School,
  backpack: Backpack,
  pencil: Pencil,
  writing: Pencil,
  calculator: Calculator,
  accounting: Calculator,

  // Семья и дети
  baby: Baby,
  kids: Baby,
  children: Baby,
  infant: Baby,
  'person-standing': PersonStanding,
  person: PersonStanding,
  child: PersonStanding,
  users: Users,
  family: Users,
  group: Users,

  // Питомцы
  dog: Dog,
  pets: Dog,
  cat: Cat,
  bird: Bird,
  rabbit: Rabbit,
  turtle: Turtle,
  'paw-print': PawPrint,
  paw: PawPrint,
  bone: Bone,

  // Путешествия и подарки
  plane: Plane,
  travel: Plane,
  vacation: Plane,
  flight: Plane,
  gift: Gift,
  gifts: Gift,
  present: Gift,

  // Алкоголь и табак
  beer: Beer,
  alcohol: Beer,
  cafe: Coffee,
  cigarette: Cigarette,
  smoking: Cigarette,
  tobacco: Cigarette,

  // Финансы
  'credit-card': CreditCard,
  credit: CreditCard,
  loans: CreditCard,
  'piggy-bank': PiggyBank,
  savings: PiggyBank,
  'trending-up': TrendingUp,
  investments: TrendingUp,
  stocks: TrendingUp,
  'shield-check': ShieldCheck,
  insurance: ShieldCheck,
  receipt: Receipt,
  taxes: Receipt,
  bill: Receipt,

  // Доходы
  banknote: Banknote,
  salary: Banknote,
  'circle-dollar-sign': CircleDollarSign,
  'dollar-sign': DollarSign,
  income: CircleDollarSign,
  bonus: Gift,

  // Техника и электроника
  monitor: Monitor,
  display: Monitor,
  laptop: Laptop,
  computer: Laptop,
  printer: Printer,
  mouse: Mouse,
  keyboard: Keyboard,
  'hard-drive': HardDrive,
  storage: HardDrive,

  // Дом и мебель
  bed: Bed,
  bedroom: Bed,
  sofa: Sofa,
  furniture: Sofa,
  lamp: Lamp,
  lighting: Lamp,
  bath: Bath,
  bathroom: Bath,
  'washing-machine': WashingMachine,
  laundry: WashingMachine,
  refrigerator: Refrigerator,
  fridge: Refrigerator,
  microwave: Microwave,

  // Природа и сад
  'tree-pine': TreePine,
  tree: TreePine,
  nature: TreePine,
  flower2: Flower2,
  flower: Flower2,
  flowers: Flower2,
  leaf: Leaf,
  leaves: Leaf,
  plant: Sprout,
  garden: Sprout,

  // Погода и климат
  flame: Flame,
  fire: Flame,
  heating: Flame,
  snowflake: Snowflake,
  cold: Snowflake,
  cooling: Snowflake,
  sun: Sun,
  sunny: Sun,
  summer: Sun,
  cloud: Cloud,
  weather: Cloud,
  umbrella: Umbrella,
  rain: Umbrella,

  // Прочее
  wrench: Wrench,
  repairs: Wrench,
  maintenance: Wrench,
  tools: Wrench,
  'help-circle': HelpCircle,
  other: HelpCircle,
  misc: HelpCircle,
  wallet: Wallet,
}

/**
 * Получить компонент иконки по имени
 * @param iconName - название иконки (например, 'shopping-cart', 'utensils')
 * @returns React компонент иконки из Lucide
 */
export function getIconByName(iconName: string): LucideIcon {
  const normalized = iconName.toLowerCase().trim()
  return ICON_REGISTRY[normalized] || HelpCircle
}
